### ISSUE TITLE
问个代码实现的小问题

### ISSUE THREAD

**Issue by behappyforever** [xue8/yohttp#3]
cn.ddnd.yohttp.executor.Dispatcher#executor
有关调度中心在执行task的逻辑代码，如下实现，当任务为空时为让线程空转。
为什么不选择使用blockqueue的take() 取任务，当无任务时调度线程得以让出cpu资源
while (true) {
                    while (chainQueue.size() > 0) {
                        executorService.submit(new CallRunnable(chainQueue.pollChain()));
                    }
}

**Comment by xue8** [comment]
谢谢提醒，已换成 take()。
